In [5]:
import pandas as pd

gold = pd.read_parquet("../data/gold/indicador_municipio.parquet")

print(gold.shape)

gold.head()

(23995, 15)

,ano,id_municipio,municipio,rede,taxa_alfabetizacao,media_portugues,nivel_alfabetizacao,percentual_participacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030
0,2023,1100015,Alta Floresta D'Oeste,Municipal,64.55,758.3304,3,89.37,67.08,69.51,71.84,74.06,76.16,78.14,80.0
1,2023,1100015,Alta Floresta D'Oeste,Pública (Estadual e Municipal),64.55,758.3304,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,1100023,Ariquemes,Municipal,62.30,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.90,80.0
3,2023,1100023,Ariquemes,Pública (Estadual e Municipal),62.30,757.0999,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,1100031,Cabixi,Municipal,69.10,767.8763,3,90.48,70.85,72.53,74.15,75.71,77.21,78.64,80.0

In [6]:
gold.duplicated(
    subset=["ano", "id_municipio", "rede"]
).sum()

np.int64(0)

In [ ]:
meta_alfabetizacao_municipio = pd.read_parquet("../data/silver/meta_alfabetizacao_municipio.parquet")

meta_alfabetizacao_municipio.head(10)

,ano,id_municipio,id_municipio_nome,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao,percentual_participacao
0,2023,1100015,Alta Floresta D'Oeste,Municipal,64.6,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3,89.37
1,2023,1100023,Ariquemes,Municipal,62.3,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3,89.79
2,2023,1100031,Cabixi,Municipal,69.1,70.85,72.53,74.15,75.71,77.21,78.64,80.0,3,90.48
3,2023,1100049,Cacoal,Municipal,62.5,65.39,68.16,70.81,73.33,75.70,77.92,80.0,3,84.44
4,2023,1100056,Cerejeiras,Municipal,58.5,62.09,65.53,68.81,71.91,74.81,77.51,80.0,2,92.12
5,2023,1100064,Colorado do Oeste,Municipal,62.9,65.67,68.39,70.98,73.45,75.78,77.96,80.0,3,86.98
6,2023,1100072,Corumbiara,Municipal,58.2,61.82,65.31,68.64,71.79,74.74,77.48,80.0,2,92.25
7,2023,1100080,Costa Marques,Municipal,80.7,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5,91.06
8,2023,1100098,Espigão D'Oeste,Municipal,85.3,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5,93.39
9,2023,1100106,Guajará-Mirim,Municipal,41.8,47.82,53.95,59.97,65.69,71.00,75.78,80.0,1,94.52

Durante a construção da camada Gold foi identificado que as tabelas de metas
(`meta_alfabetizacao_brasil`, `meta_alfabetizacao_uf` e
`meta_alfabetizacao_municipio`) armazenam metas futuras em formato wide
(uma coluna para cada ano).

In [30]:
comparativo = pd.read_parquet(
    "../data/gold/comparativo_metas.parquet"
)

comparativo.tail(15)

,nivel_geografico,ano_origem,ano_meta,uf,id_municipio,municipio,rede,taxa_alfabetizacao,nivel_alfabetizacao,percentual_participacao,meta_alfabetizacao
75501,UF,2025,2030,MT,<NA>,<NA>,Pública,75.0,<NA>,94.0,80.0
75502,UF,2025,2030,PA,<NA>,<NA>,Pública,58.0,<NA>,87.0,80.0
75503,UF,2025,2030,PB,<NA>,<NA>,Pública,71.0,<NA>,90.0,80.0
75504,UF,2025,2030,PE,<NA>,<NA>,Pública,66.0,<NA>,93.0,80.0
75505,UF,2025,2030,PI,<NA>,<NA>,Pública,77.0,<NA>,94.0,80.0
75506,UF,2025,2030,PR,<NA>,<NA>,Pública,80.0,<NA>,87.0,80.0
75507,UF,2025,2030,RJ,<NA>,<NA>,Pública,60.0,<NA>,83.0,80.0
75508,UF,2025,2030,RN,<NA>,<NA>,Pública,48.0,<NA>,85.0,80.0
75509,UF,2025,2030,RO,<NA>,<NA>,Pública,75.0,<NA>,79.0,80.0
75510,UF,2025,2030,RR,<NA>,<NA>,Pública,57.0,<NA>,82.0,80.0
75511,UF,2025,2030,RS,<NA>,<NA>,Pública,52.0,<NA>,86.0,80.0
75512,UF,2025,2030,SC,<NA>,<NA>,Pública,59.0,<NA>,87.0,80.0
75513,UF,2025,2030,SE,<NA>,<NA>,Pública,50.0,<NA>,87.0,80.0
75514,UF,2025,2030,SP,<NA>,<NA>,Pública,61.0,<NA>,89.0,80.0
75515,UF,2025,2030,TO,<NA>,<NA>,Pública,61.0,<NA>,89.0,80.0

In [29]:
comparativo.shape

(75516, 11)

In [26]:
comparativo["nivel_geografico"].value_counts()

nivel_geografico
Município    74928
UF             567
Brasil          21
Name: count, dtype: int64

In [27]:
comparativo.groupby(
    "nivel_geografico"
)["ano_meta"].value_counts().sort_index()

nivel_geografico  ano_meta
Brasil            2024            3
                  2025            3
                  2026            3
                  2027            3
                  2028            3
                  2029            3
                  2030            3
Município         2024        10704
                  2025        10704
                  2026        10704
                  2027        10704
                  2028        10704
                  2029        10704
                  2030        10704
UF                2024           81
                  2025           81
                  2026           81
                  2027           81
                  2028           81
                  2029           81
                  2030           81
Name: count, dtype: int64

In [35]:
evolucao = pd.read_parquet(
    "../data/gold/evolucao_temporal.parquet"
)

evolucao.head(15)

,nivel_geografico,ano,uf,id_municipio,municipio,rede,taxa_alfabetizacao,media_portugues,nivel_alfabetizacao,percentual_participacao
0,Brasil,2023,<NA>,<NA>,<NA>,Pública,55.90,NaN,<NA>,86.00
1,Brasil,2024,<NA>,<NA>,<NA>,Pública,59.20,NaN,<NA>,87.37
2,Brasil,2025,<NA>,<NA>,<NA>,Pública,66.00,NaN,<NA>,88.00
3,Município,2023,<NA>,1100015,Alta Floresta D'Oeste,Municipal,64.55,758.3304,<NA>,NaN
4,Município,2023,<NA>,1100015,Alta Floresta D'Oeste,Pública (Estadual e Municipal),64.55,758.3304,<NA>,NaN
5,Município,2023,<NA>,1100023,Ariquemes,Municipal,62.30,757.0999,<NA>,NaN
6,Município,2023,<NA>,1100023,Ariquemes,Pública (Estadual e Municipal),62.30,757.0999,<NA>,NaN
7,Município,2023,<NA>,1100031,Cabixi,Municipal,69.10,767.8763,<NA>,NaN
8,Município,2023,<NA>,1100031,Cabixi,Pública (Estadual e Municipal),69.10,767.8763,<NA>,NaN
9,Município,2023,<NA>,1100049,Cacoal,Estadual,66.13,761.9918,<NA>,NaN
10,Município,2023,<NA>,1100049,Cacoal,Municipal,62.51,755.5645,<NA>,NaN
11,Município,2023,<NA>,1100049,Cacoal,Pública (Estadual e Municipal),63.37,757.0954,<NA>,NaN
12,Município,2023,<NA>,1100056,Cerejeiras,Municipal,58.53,746.4629,<NA>,NaN
13,Município,2023,<NA>,1100056,Cerejeiras,Pública (Estadual e Municipal),58.53,746.4629,<NA>,NaN
14,Município,2023,<NA>,1100064,Colorado do Oeste,Municipal,62.85,756.9294,<NA>,NaN

In [36]:
indicador = pd.read_parquet("../data/gold/indicador_municipio.parquet")

duplicados = indicador.duplicated(
    subset=[
        "ano",
        "id_municipio",
        "rede",
    ]
)

print(f"Duplicados: {duplicados.sum():,}")

Duplicados: 0

In [37]:
indicador.groupby(
    [
        "ano",
        "id_municipio",
        "rede",
    ]
).size().describe()

count    23995.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [38]:
sorted(indicador["rede"].unique())

['Estadual',
 'Municipal',
 'Pública (Estadual e Municipal)',
 'Total (Federal, Estadual, Municipal e Privada)']

In [39]:
alunos = pd.read_parquet("../data/silver/alunos.parquet")

print("Redes dos alunos")
print(sorted(alunos["rede"].unique()))

print()

print("Redes do indicador")
print(sorted(indicador["rede"].unique()))

Redes dos alunos
['Estadual', 'Municipal', 'Privada']

Redes do indicador
['Estadual', 'Municipal', 'Pública (Estadual e Municipal)', 'Total (Federal, Estadual, Municipal e Privada)']

In [40]:
teste = alunos.merge(
    indicador[
        [
            "ano",
            "id_municipio",
            "rede",
            "taxa_alfabetizacao",
        ]
    ],
    how="left",
    on=[
        "ano",
        "id_municipio",
        "rede",
    ],
)

print(f"Linhas antes : {len(alunos):,}")
print(f"Linhas depois: {len(teste):,}")

Linhas antes : 3,867,999
Linhas depois: 3,867,999

In [42]:
sem_match = teste["taxa_alfabetizacao"].isna().sum()

print(f"Alunos sem indicador: {sem_match:,}")

print(f"Percentual: {sem_match / len(teste):.2%}")

Alunos sem indicador: 4,199
Percentual: 0.11%

In [44]:
alunos = pd.read_parquet(
    "../data/gold/alunos_modelagem.parquet"
)

alunos.head(15)

,ano,id_municipio,id_municipio_nome,id_escola,id_aluno,caderno,serie,rede,presenca,preenchimento_caderno,...,media_portugues,nivel_alfabetizacao,percentual_participacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030
0,2023,1100023,Ariquemes,60000062,11000001,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
1,2023,1100023,Ariquemes,60000062,11000002,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
2,2023,1100023,Ariquemes,60000062,11000003,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
3,2023,1100023,Ariquemes,60000062,11000004,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
4,2023,1100023,Ariquemes,60000062,11000005,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
5,2023,1100023,Ariquemes,60000062,11000006,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
6,2023,1100023,Ariquemes,60000062,11000007,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
7,2023,1100023,Ariquemes,60000062,11000008,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
8,2023,1100023,Ariquemes,60000062,11000009,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
9,2023,1100023,Ariquemes,60000062,11000010,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
10,2023,1100023,Ariquemes,60000062,11000011,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
11,2023,1100023,Ariquemes,60000062,11000012,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
12,2023,1100023,Ariquemes,60000062,11000013,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
13,2023,1100023,Ariquemes,60000062,11000014,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0
14,2023,1100023,Ariquemes,60000062,11000015,10,2° ano do Ensino Fundamental,Municipal,Presente,Prova preenchida,...,757.0999,3,89.79,65.22,68.02,70.71,73.25,75.65,77.9,80.0

In [3]:
import pandas as pd

df = pd.read_parquet("../data/gold/indicador_municipio.parquet")

df.loc[
    (df.id_municipio=="4315073")
    & (df.ano==2024)
    & (df.rede=="Municipal"),
    ["media_portugues"]
]

       media_portugues
22605           773.41